version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:5173"
    environment:
      - VITE_API_URL=https://sakhi.jnwn.xyz/api
    networks:
      - sakhi_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8005:8000"
    volumes:
      - ./backend:/app
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    networks:
      - sakhi_net

networks:
  sakhi_net:
    driver: bridge
